---
# backuppc_server tasks to configure Apache2 for BackupPC access

- name: APACHE2_MODULE | Add module
  apache2_module:
    name: "{{ module }}"
    state: present
  loop:
  - rewrite
  - ssl
  loop_control:
    loop_var: module
    
- name: TEMPLATE | Copy apache config
  template:
    dest: "/etc/apache2/sites-available/{{ backuppc_server_name }}.conf"
    src: etc/apache/apache.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: BackupPC_server - restart apache2

- name: FILE | Remove default apache2 site.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: BackupPC_server - restart apache2
  when: backuppc_disable_apache_default_site | bool

- name: FILE | Activate custom Backuppc apache site.
  file:
    path: "/etc/apache2/sites-enabled/{{ backuppc_server_name }}.conf"
    src: "/etc/apache2/sites-available/{{ backuppc_server_name }}.conf"
    state: link
  notify: BackupPC_server - restart apache2

- name: LINEINFILE | Allow distant access to Apache2 BackupPC interface
  lineinfile:
    path: '{{ backuppc_server_config_dir }}/apache.conf'
    regex: '{{ "^(\s)#?\s*(Require local.*)$" | regex_escape() }}'
    line: '{{ "\0# \1" | regex_escape() }}'
  notify: BackupPC_server - restart apache2
  when: not backuppc_apache_local | bool

- name: LINEINFILE | Require SSL to access to Apache2 BackupPC interface
  lineinfile:
    path: '{{ backuppc_server_config_dir }}/apache.conf'
    regex: '{{ "^(\s)#?\s*SSLRequireSSL" | regex_escape() }}'
    line: '{{ "\0SSLRequireSSL" | regex_escape() }}'
  notify: BackupPC_server - restart apache2
  when: backuppc_apache_require_ssl | bool

...
