---

# Copiamos los bash de respaldo al contenedor

- name: Copy bash to backup
  sudo: yes
  copy:
    src: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/files/backuppc/respaldo.sh"
    dest: /var/lib/backuppc/respaldo.sh
    owner: backuppc
    group: backuppc
    mode: 0766
  when: mysql_state.stat.exists != false and backup_mysql_dump == true

- name: Copy bash to delete_backup
  sudo: yes
  copy:
    src: "{{ playbook_dir }}/host_vars/{{ inventory_hostname}}/files/backuppc/end_respaldo.sh"
    dest: /var/lib/backuppc/end_respaldo.sh
    owner: backuppc
    group: backuppc
    mode: 0766
  when: mysql_state.stat.exists != false and backup_mysql_dump == true

