---
# Tasks to configure htpasswd users

- name: HTPASSWD | Configure web access BackupPC user password
  htpasswd:
    path: '{{ backuppc_srv_config_dir }}/htpasswd'
    name: "{{ backuppc_srv_web_user.name }}"
    password: "{{ backuppc_srv_web_user.password }}"
    owner: root
    group: '{{ backuppc_srv_unix_group }}'
    mode: 0640
  when: backuppc_srv_web_user.password is defined

- name: LINEINFILE | Configure web access BackupPC user password hash code
  lineinfile:
    path: '{{ backuppc_srv_config_dir }}/htpasswd'
    regexp: '{{ backuppc_srv_web_user.htpasswd_hash }}'
    line: '{{ backuppc_srv_web_user.htpasswd_hash }}'
    state: present
  when: backuppc_srv_web_user.htpasswd_hash is defined

- name: LINEINFILE | Configure BackupPC user mail alias
  lineinfile:
    path: /etc/aliases
    regexp: '^{{ backuppc_srv_web_user.name}}:'
    line: '{{ backuppc_srv_web_user.name}}: {{ backuppc_srv_web_user.mail }}'
    state: present
  when: backuppc_srv_web_user.mail is defined

...
