---

- name: APT | Install BackupPC and few related tools
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - backuppc
    - fcgiwrap
    - libfile-rsyncp-perl
    - ohai
    - python-passlib
  register: install

- name: SETUP | with ohai
  action: setup
  when: install.changed

- name: crear usuario backuppc
  htpasswd:
    path: /etc/backuppc/htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ users_backuppc }}"
  tags: create_users_backuppc

- name: USER | Create SSH key for backuppc user
  user: >
    name=backuppc
    generate_ssh_key=yes
    ssh_key_bits={{ backuppc_ssh_key_bits | default (omit) }}
    ssh_key_comment=backuppc@{{ inventory_hostname }}

- name: TEMPLATE | Global BackupPC configuration
  template: >
    src=etc/backuppc/config.pl.j2
    dest='/etc/backuppc/config.pl'   
    owner=backuppc
    group=www-data
    mode=0640
  notify: 
  - restart backuppc
  - restart apache2
