---

- name: APT | Install BackupPC and few related tools
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - backuppc
    - fcgiwrap
    - libfile-rsyncp-perl
    - ohai
    - python-passlib
  register: install

- name: SETUP | with ohai
  action: setup
  when: install.changed

- name: crear usuario backuppc
  htpasswd:
    path: /etc/backuppc/htpasswd
    name: backuppc
    password: "{{ backuppc_web_password }}"
    owner: root
    group: www-data
    mode: 0640

- name: USER | Create SSH key for backuppc user
  user: >
    name=backuppc
    generate_ssh_key=yes
    ssh_key_bits={{ backuppc_ssh_key_bits | default (omit) }}
    ssh_key_comment=backuppc@{{ backuppc_server_name }}
