---
## backuppc installation

- name: FILE | Create symbolic link 
  file:
    src: "{{ backuppc_home_link }}"
    dest: "{{ backuppc_server_home }}"
    mode: 0755
    state: link
  when: backuppc_home_link is defined
  tags: symbolic

- name: APT | Install BackupPC and few related tools
  apt: 
    pkg: '{{ packages }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - backuppc
    - fcgiwrap
    - libfile-rsyncp-perl
    - ohai
    - python-passlib
    - rsync
    - ssl-cert
  register: backuppc_install

- name: SETUP | with ohai
  action: setup
  when: backuppc_install.changed

- name: INCLUDE | Configure htpasswd users
  include_tasks: htpasswd_users.yml
  loop: "{{ backuppc_server_web_users }}"
  loop_control:
    loop_var: backuppc_server_web_user
  tags: backuppc_config_users

- name: USER | Create SSH key for backuppc user
  user:
    name: '{{ backuppc_server_user }}'
    generate_ssh_key: yes
    ssh_key_bits: "{{ backuppc_server_user_ssh_key_bits | default (omit) }}"
    ssh_key_comment: "{{ backuppc_server_user }}@{{ inventory_hostname }}"

- name: TEMPLATE | Global BackupPC configuration
  template:
    src: etc/backuppc/config.pl.j2
    dest: '{{ backuppc_server_config_dir }}/config.pl'   
    owner: '{{ backuppc_server_user }}'
    group: '{{ backuppc_server_group }}'
    mode: 0640
  notify: 
  - BackupPC_server - restart backuppc
  - BackupPC_server - restart apache2
...