---
# Main tasks of backuppc_server role

- name: IMPORT_TASKS | Install BackupPC
  import_tasks: install.yml

- name: IMPORT_TASKS | Config Apache2
  import_tasks: apache.yml
  when: backuppc_srv_configure_apache | bool

...
