---

- name: INCLUDE | Install
  include: install.yml
  when: inventory_hostname in groups.seciu_backuppc

- name: config user mysql 
  include_tasks: pc_backups.yml
  when: inventory_hostname in groups.seciu_backup and backup_config_mysql

- name: add file bash
  include_tasks: copy_bash.yml
  when: inventory_hostname in groups.seciu_backup

- name: INCLUDE | Configuration
  include: config.yml
  when: inventory_hostname in groups.seciu_backup

- name: INCLUDE | SSH related configuration
  include: ssh.yml
  when: inventory_hostname in groups.seciu_backup
