---
# Se corre la instalacion de todo lo requerido para respaldar los contenedores, se crea usuario mysql para respaldar las BD 
# Asignamos permisos para el usuario mysql

- name: Instalar Rsync
  apt:
    name: rsync
    state: present
 
- name: Create user
  user:
    name: backuppc
    home: /var/lib/backuppc
    shell: /bin/bash

- name: Create dir
  file:
    path: /var/lib/backuppc/.ssh
    state: directory
    owner: backuppc
    group: backuppc
    mode: 0700

- name: Check if Service Exists 
  stat: path=/etc/init.d/mysql
  register: mysql_state

- name: Start service mysql, if not started
  service:
    name: mysqld
    state: started
  when: mysql_state.stat.exists != false

- name: Install MySQL-Python  module
  apt: name=python-mysqldb state=present
  when: mysql_state.stat.exists != false

- name: Empty file /etc/my.cnf
  shell: cat /dev/null > /etc/mysql/conf.d/my.cnf
  when: mysql_state.stat.exists != false

- name: LINEINFILE | Add access to mysql 
  lineinfile: >
    dest=/etc/mysql/conf.d/my.cnf
    line="[client] \n user={{mysql_user}} \n password={{vault_root_pass_mysql}} \n port=3306 \n host=localhost"
    regexp="^user=backuppc"
    state={{'present'}}
  when: mysql_state.stat.exists != false

- name: Set user privileges
  mysql_user:
    login_user: root
    login_password: "{{ vault_root_pass_mysql }}"
    user: "{{ mysql_user }}"
    password: "{{ vault_root_pass_mysql }}"
    state: present
    priv: '*.*:ALL,GRANT'
  when: mysql_state.stat.exists != false

