---

- name: Instalar Rsync
  apt:
    name: rsync
    state: present
 
- name: Create user
  user:
    name: backuppc
    home: /var/lib/backuppc
    shell: /bin/bash

- name: Create dir
  file:
    path: /var/lib/backuppc/.ssh
    state: directory
    owner: backuppc
    group: backuppc
    mode: 0744

- name: Check if Service Exists
  stat: path=/etc/init.d/mysql
  register: register

- name: Install MySQL-Python  module
  apt: name=python-mysqldb state=present
  when: register.stat.exists != false

- name: Empty file /etc/my.cnf
  shell: cat /dev/null > /etc/my.cnf

- name: LINEINFILE | Add access to mysql 
  lineinfile: >
    dest=/etc/my.cnf
    line="[client] \n user={{mysql_user}} \n password={{vault_root_pass_mysql}} \n port=3306 \n host=localhost"
    regexp="^user=backuppc"
    state={{'present'}}
  when: register.stat.exists != false

- name: Set user privileges
  mysql_user:
    login_user: root
    login_password: "{{ vault_root_pass_mysql }}"
    user: "{{ mysql_user }}"
    password: "{{ vault_root_pass_mysql }}"
    state: present
    priv: '*.*:ALL,GRANT'
    #priv: 'somedatabase.*:ALL/someotherdatabase.*:ALL/*.*:SUPER,RELOAD,SHOW DATABASES'
  when: register.stat.exists != false

- name: copiar bash de respaldo
  sudo: yes
  copy:
    src: "{{ playbook_dir }}/host_vars/{{ inventory_hostname}}/files/respaldo.sh"
    dest: /var/lib/backuppc/respaldo.sh

    owner: backuppc
    group: backuppc
    mode: 0766
  when: register.stat.exists != false and inventory_hostname in groups.seciu_backup_dump

- name: copiar bash de delete_respaldo
  sudo: yes
  copy:
    src: "{{ playbook_dir }}/host_vars/{{ inventory_hostname}}/files/delete_respaldo.sh"
    dest: /var/lib/backuppc/delete_respaldo.sh
    owner: backuppc
    group: backuppc
    mode: 0766
  when: register.stat.exists != false and inventory_hostname in groups.seciu_backup_dump

