---

- name: COMMAND | Show SSH pub key
  command: "cat {{ ohai_etc.passwd.backuppc.dir }}/.ssh/id_rsa.pub"
  register: cat
  changed_when: false

- name: Add SSH pub key for hosts
  sudo: yes
  authorized_key:
    user: backuppc
    state: present
    key: "{{ cat.stdout }}"
  delegate_to: "{{ item }}"
  with_items: "{{ hostname_backup }}"

- name: Empty file /etc/my.cnf
  shell: cat /dev/null > /var/lib/backuppc/.ssh/known_hosts

- name: Add host to known_hosts
  shell: "ssh-keyscan -H {{ item }} >> /var/lib/backuppc/.ssh/known_hosts"
  with_items: "{{ hostname_backup }}"

- name: DEBUG | SSH pub key
  debug: var=cat.stdout
