---
# backuppc_server role's handlers

- name: BackupPC_server - restart backuppc
  service: 
    name: backuppc
    state: restarted
    enabled: yes

- name: BackupPC_server - restart apache2
  service: 
    name: apache2
    state: restarted
    enabled: yes

...
